apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgBLpx/mtdQj1ec05nB8TiyVgEPOwChKI2PYjMaJQT1B/sxklPEkw5wvCeSOftamLA1kyuhOqH+yXlwvMOVoIG2JbK3CTCjXneWPug4Or5AKjmJ7Nwx4XPtexQ4v2LgQzOlydCPUdx4kieptPuyUAH9y+NBgyygaZy12Ch7P5U0HNJqTmIEWOWO1DcD80lUZlYzepkXrbY4+TZeZ6PXyTv6Mq8BBSqGn50Bc7I6vYKj2MRiTcfgmSCkVAQgi798L2J36RIwjtKxt58DwxIeIR9ZD63ZbSIOWz2L+JqpYMnUvBfhOwqV0EF92rlNtOEY0cuM15VEJI2Tx2gJdNl4ckjk4RmzyCMU0DcSy14sQf8pAykyZQO9hwi7rvM3liOkYVrK9spH3HSl0CmMGA9n0WHvubw+F9Wc615+jLpwzjIqggU2r1MfzmU1wkFH/BeyEcZPaMluSnha/GTqN8lHiaieLfP6mjCNATtL+svKr7UWkmLJu6aWtnpReac0RdlrhKPRIeno5nHEynVmfP3hMvHlVJBuLDoQ2CkCZ02DJBLI5KJ5TE1J3BFAqCh0Vc3XTjUeZ7rWfzFZF69OEPk2A54TV8OtRIaSosoqw44pJUpKsfVFW2p7Zu7F7jYjSHwDWV2gNM0u9eM7pd/fI6NMRXXFppN+JsU71bUCcfmBmG7Zd2tJPLlIX++2drK9HcYIahmOL3KN6ow==
    user: AgCQX4MFEGjd7ijFSucDrCuSWGPOPQJV1n1hfuegb1YBEx8dQIlMzviR3/7+PrdvDi+nv5Mlkq/+GitZrSxqxN0b+TqYnO0tG/thpnEh/MxLeBpLudxQbxlO8tjwhO7DuJGr4q5BjsbcTAiApi3EZZ81e55ORO112x8FEhdP1BkZfVCJF+H7mmYF1SEs8ZOUiZLPGO2IODXaJnq23thJ7EOwpIHNz/I4qpQSdWP6SRhu3g94DXHrVyeF49OeT88+wG0xLWnROJL1IzcpDzXzUpVwq+iLz1wC1rgyYVK71PGwujMb+E8TONcq0U/2EauJFRCmDWurPcuzVwdWCIasIoaVpvD71zaW5KWBK1deyHlrpbssmTaulc4U0sFOkcw++l+C8PAnzYTFLMR6hyDatx2HijyYhXrI39obijLyDtW49ilJWkbFxBNY9K724leyS4txdzktFnSiEFfgaNYu994uesG4ev4Zfx8rS+kS6/FhZG6RRzYgCMa7vZDLlqzx+UelmLarGJQjlhHK/rAx0iYFLVIcNfsDj952LEramzWyi52vDrocB33k73rqQJa9M8JS4QImzxrrqUyqWXqXtcXf1vK2XIPkQGnA2JfL1jnMqnvRigEDF1+kHHB24YpLGxAz19ae9wAlrpTzHu9coKG655uaqNg8Z9N1VQIB3CY9duCHJjZWjspj3mHYqhFlr79oS4+ZvA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod

